version: '3.8'

services:  
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - 80:80
      - 81:81
      - 82:82