version: '3.9'

services:
  frontend:
    image: frontend-custom:latest
    pull_policy: never
    restart: always
    container_name: 'frontend'
    ports:
      - "3000:3000"
    env_file:
      -  ../envs/common-frontend.env
    environment:
      - NODE_ENV=development
    # For debugging: uncomment to enable volume mounting for live code changes
    # volumes:
    #   - /Users/sankanvicha/Desktop/project/blockscout-frontend:/app
