version: '3.9'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
      - "../certbot/conf:/etc/nginx/ssl"
      - "../certbot/data:/var/www/certbot"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
      - target: 443
        published: 443
    depends_on:
      - certbot
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/data:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email hamdee@six.network --agree-tos --no-eff-email -d devnet.evm.sixscan.io
    restart: unless-stopped