version: '3.9'

services:
  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    ports:
      - 8081:8050

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    ports:
      - 8083:8050
    

  sc-verifier:
    extends:
      file: ./services/smart-contract-verifier.yml
      service: smart-contract-verifier
    ports:
      - 8082:8050

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
    extends:
      file: ./services/stats.yml
      service: stats
    ports:
      - 8080:8050
