name: Cleanup environments

on:
  pull_request:
    types:
      - closed
      - merged
  workflow_dispatch:

jobs:
  cleanup:
    uses: blockscout/blockscout-ci-cd/.github/workflows/cleanup.yaml@master
    with:
      appNamespace: review-blockscout-$GITHUB_REF_SLUG
    secrets: inherit
